"""add coding platform (problems + submissions)

Creates `coding_problems` + `coding_submissions` tables for the V1 coding
practice platform. Extends `xp_event_type` Postgres enum with the
`coding_problem_solved` value (SQLite uses a permissive VARCHAR + CHECK so it's
effectively a no-op there; `Base.metadata.create_all` regenerates the CHECK on
next run).

Revision ID: 000000000004
Revises: 000000000003
Create Date: 2026-05-11 10:00:00.000000
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "000000000004"
down_revision: Union[str, Sequence[str], None] = "000000000003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    dialect = bind.dialect.name

    # Extend the XP-event-type enum on Postgres (no-op on SQLite — the CHECK
    # constraint is regenerated by Base.metadata.create_all on dev boots).
    if dialect == "postgresql":
        op.execute("ALTER TYPE xp_event_type ADD VALUE IF NOT EXISTS 'coding_problem_solved'")

    op.create_table(
        "coding_problems",
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("slug", sa.String(length=100), nullable=False, unique=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum("easy", "medium", "hard", name="coding_difficulty"),
            nullable=False,
        ),
        sa.Column("function_name", sa.String(length=100), nullable=False),
        sa.Column("function_signature", sa.JSON(), nullable=False),
        sa.Column("examples", sa.JSON(), nullable=False),
        sa.Column("hints", sa.JSON(), nullable=False),
        sa.Column("starter_code", sa.JSON(), nullable=False),
        sa.Column("reference_solution", sa.JSON(), nullable=False),
        sa.Column("visible_test_cases", sa.JSON(), nullable=False),
        sa.Column("hidden_test_cases", sa.JSON(), nullable=False),
        sa.Column("comparator", sa.String(length=20), nullable=False, server_default="exact"),
        sa.Column("topic_tags", sa.JSON(), nullable=False),
        sa.Column("skill_node_names", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_coding_problems_slug", "coding_problems", ["slug"], unique=True)
    op.create_index("ix_coding_problems_difficulty", "coding_problems", ["difficulty"])

    op.create_table(
        "coding_submissions",
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column(
            "user_id",
            sa.UUID(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "problem_id",
            sa.UUID(),
            sa.ForeignKey("coding_problems.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "language",
            sa.Enum("python", "cpp", "java", name="coding_language"),
            nullable=False,
        ),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("passed", "failed", "error", name="coding_submission_status"),
            nullable=False,
        ),
        sa.Column("passed_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("total_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("runtime_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_coding_submissions_user_id", "coding_submissions", ["user_id"])
    op.create_index("ix_coding_submissions_problem_id", "coding_submissions", ["problem_id"])
    op.create_index("ix_coding_submissions_status", "coding_submissions", ["status"])


def downgrade() -> None:
    op.drop_index("ix_coding_submissions_status", table_name="coding_submissions")
    op.drop_index("ix_coding_submissions_problem_id", table_name="coding_submissions")
    op.drop_index("ix_coding_submissions_user_id", table_name="coding_submissions")
    op.drop_table("coding_submissions")
    op.drop_index("ix_coding_problems_difficulty", table_name="coding_problems")
    op.drop_index("ix_coding_problems_slug", table_name="coding_problems")
    op.drop_table("coding_problems")

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        sa.Enum(name="coding_submission_status").drop(bind, checkfirst=True)
        sa.Enum(name="coding_language").drop(bind, checkfirst=True)
        sa.Enum(name="coding_difficulty").drop(bind, checkfirst=True)
        # NOTE: cannot drop an added enum value from xp_event_type — Postgres
        # has no `ALTER TYPE … DROP VALUE`. Leave it in place; it's harmless.
